site_name: Functional Reactive with Java
site_url: http://www.functional-reactive.org
repo_url: https://github.com/functional-reactive/functional-reactive.github.io.git
##repo_name: GitHub
site_author: Sven Ruppert
google_analytics: ['UA-88569541-1', 'Functional-Reactive']

theme: readthedocs
markdown_extensions:
    - toc:
        permalink: True
pages:
- Home: index.md
- Core: core.md
- Basics: basics.md
- Functional: functional.md
- Memoizing: functional_result.md
- Memoizing: functional_memoizing.md
- Pattern: pattern.md
- Reactive: reactive.md
